name: moods
favicon: null
layout_spectrum: 0.50189
typography_spectrum: 0.94572
title: Moods
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efefe5'
    - '#8e8e8e'
    - '#8fb9a5'
    - '#5c5c5c'
    - '#010000'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
