name: moods
favicon: null
layout_spectrum: 0.00316
typography_spectrum: 0.94572
title: Moods
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e2dd'
    - '#56524f'
    - '#373330'
    - '#888481'
    - '#bdb6b1'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
